title: GroupNews Documentation
description: Answering your questions about how to use GroupNews.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
permalink: pretty

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo-documentation.svg"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
# "Just the Docs on GitHub":
#   - "https://github.com/pmarsceill/just-the-docs"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2021 GroupNews LLC."

# Color scheme currently only supports "dark" or nil (default)
color_scheme: groupnews

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: #UA-2709176-10

plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    docs:
      # Give the collection a name
      name: Documentation
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
